apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: leader
    tier: backend


#This manifest file creates a Service named redis-leader with a set of labels that match the labels previously defined,
#so the Service routes network traffic to the Redis Pod.
